<a href="https://colab.research.google.com/github/sandip01234/MachineLearning/blob/main/firstclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to numpy



.Creating an array.✅
.Multidimenisional Array.✅
.Randonmly generated arrays.✅
.Element wise operation.
.Summerizing operations.





## Single dimensional array


In [ ]:
import numpy as np


In [ ]:
#Create an array with all  the elements  to be zeros
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [ ]:
#Creating an array with all elements to be ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#Creating an array of size 10 with all elements 69
np.full(10, 69)

array([69, 69, 69, 69, 69, 69, 69, 69, 69, 69])

In [ ]:
np.array([1, 2, 3, 4, 5, 8])

array([1, 2, 3, 4, 5, 8])

In [ ]:
#array with starting and ending .
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [ ]:
#create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimensional array:


In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
x= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [2, 4, 6]
])
x[0, 1]=20
print(x)


[[ 1 20  3]
 [ 4  5  6]
 [ 2  4  6]]


In [ ]:

x[2]=1
print(x)

[[ 1 20  3]
 [ 4  5  6]
 [ 1  1  1]]


In [ ]:
x[:,2]=2
print(x)

[[ 1 20  2]
 [ 4  5  2]
 [ 2  4  2]]


In [ ]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Randonmly generated array:
 .NumPy can create arrays filled with random numbers
 .To ensure the reproductibiltiy, you can set a seed using ``np.random.seed()``. It will generate the exact same random numbers for each executions.
 .If you remove or change the seed values, the sequence of random numbers will be changed.

In [ ]:
np.random.rand(5)

array([0.6851502 , 0.21165334, 0.31726607, 0.2672994 , 0.12050632])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.randn(5, 2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [ ]:
np.random.randint(low=0, high=100, size=(5, 5))

array([[98, 50, 46,  9, 24],
       [24,  1, 17, 54, 16],
       [41, 20, 31, 24, 67],
       [ 8, 91, 46, 67, 26],
       [69, 91, 27, 16, 85]])